PREFIX ifc:     <http://standards.buildingsmart.org/IFC/DEV/IFC2x3/TC1/OWL#>

# return all IFC Slabs (with types)

SELECT ?subject ?subjectType ?predicate ?object ?objectType
WHERE {
  ?subject  a  ifc:IfcSlab ;
    a ?subjectType ;
    ?predicate ?object .
  OPTIONAL { ?object a ?objectType }
}

LIMIT 30