PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT * WHERE {
    GRAPH ?versionedGraph { 
        ?subject  ?predicate  ?object ;
            a ?subjectType .
        ?object a ?objectType .
    }

    ?versionedGraph prov:specializationOf ?graph ;
        prov:atLocation ?version .
}