PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT * WHERE {
    GRAPH ?versionedGraph { 
        ?subject  ?predicate  ?object .
    }
    
    ?versionedGraph prov:specializationOf ?graph ;
        prov:atLocation ?version .

    ?subject  a ?subjectType .
    ?object a ?objectType .
}